# Generated by Django 5.1.3 on 2024-11-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matriculado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='N/A', max_length=100)),
                ('documentoid', models.CharField(max_length=100)),
                ('periodo_inscripcion', models.CharField(default='N/A', max_length=100)),
                ('direccion', models.CharField(default='N/A', max_length=100)),
                ('email', models.CharField(default='N/A', max_length=100)),
            ],
        ),
    ]
