# Generated by Django 5.1.3 on 2024-11-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculado',
            name='direccion',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='matriculado',
            name='documentoid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='matriculado',
            name='email',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='matriculado',
            name='nombre',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='matriculado',
            name='periodo_inscripcion',
            field=models.TextField(default='N/A'),
        ),
    ]
