# Generated by Django 5.1.3 on 2024-11-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matriculas', '0002_alter_matriculado_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculado',
            name='hashDireccion',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='matriculado',
            name='hashDocumentoId',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='matriculado',
            name='hashEmail',
            field=models.TextField(default='N/A'),
        ),
    ]
