# Generated by Django 3.1.12 on 2024-12-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('cuenta', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montototal', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
