# Generated by Django 5.1.3 on 2024-12-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_reporte_monto2_reporte_monto3_reporte_montototal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='monto3',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
