# Generated by Django 5.1.3 on 2024-12-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_reporte_monto3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='monto3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
