# Generated by Django 5.1.3 on 2024-12-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_alter_reporte_monto3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='montototal',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
